sudo: required #sudo is super user level permissions
language: generic 
services:
    - docker 

before_install:
    - docker build -t bruno1990/docker-react -f Dockerfile.dev . #any tag could be written

script:
    - docker run -e CI=true bruno1990/docker-react npm run test #-e CI=true is what you have to add in the code so npm test can quit instead of waiting for user input


deploy:
    provider: elasticbeanstalk #where it will be deployed, environment on AWS
    region: "pt"  #here you put the region that is set on your elasticbeanstalk environment url
    app: "docker-react" #put the name of the app created on AWS
    env: "Docker-env" #put the name of the enviroment you created with elasticbeanstalk
    bucket_name:  #put here the S3 container that was generated when you created the elasticbeanstalk instance
    bucket_path: "docker-react" #this will be the folder created on the bucket with your project so normally it is the same name has the project
    on:
        branch: master #this serves has to understand that only deploy code when the project is on the master branch inside github
    access_key_id: $AWS_ACCESS_KEY #here you will put the keys generated by elasticbeanstalk that you previously set on the Travis environment variables part
    secret_access_key: $AWS_SECRET_KEY #here you will put the keys generated by elasticbeanstalk that you previously set on the Travis environment variables part